### ISSUE TITLE
TASK [../../ : install | dependencies]

### ISSUE THREAD

**Issue by Sprbb** [Oefenweb/ansible-nagios-server#11]
fatal: [debian-7]: FAILED! => {"attempts": 3, "cache_update_time": 1574959785, "cache_updated": false, "changed": false, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"      install 'nagios3' 'python-passlib'' failed: E: There are problems and -y was used without --force-yes\n"

**Comment by tersmitten** [comment]
Debian 7 is no longer supported
