### ISSUE TITLE
Is there a way to set check_external_commands=1?

### ISSUE THREAD

**Issue by LukasGibb** [Oefenweb/ansible-nagios-server#8]
Looking at the tasks I can't see a way to set any parameters in the main nagios.cfg file. 

I want to set check_external_commands=1 so I can issue commands from CGI GUI.

Just wondering how you have done this previously, if at all?

If it's not currently possible I might just create a fork so I can add the functionality and submit a pull request.

Thanks in advance.

**Comment by tersmitten** [comment]
Can you add some documentation about `check_external_commands`?

**Comment by tersmitten** [comment]
And feel free to open a PR. I'll be happy to add the functionality.

**Comment by tersmitten** [comment]
Fixed in #10 #9
